### ISSUE TITLE
BUG: scroll to top button is not working properly!

### ISSUE THREAD

**Issue by TheNikhilRaj** [Anushkabh/krishiconnect#670] opened 2024-06-27 08:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Anushkabh ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no properly working scroll to top button present on the website.

and also i can add progress bar in the button.

![343046177-a64505c3-c4e1-432e-bd29-29228d4ab763](https://github.com/Anushkabh/krishiconnect/assets/129590267/99518242-dfaa-4030-9ac5-85e83bc24b39)
like this!!

assign me under gssoc'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment] 2024-06-30 07:42
Hello @TheNikhilRaj !

the issue is currently  been assigned to someone else and will be fixed soon.
keep looking for more issues in the repo.

happy coding ✨

**Closed by himanshu-03** 2024-06-30 07:42 UTC
