### ISSUE TITLE
BUG:Unable to insert data into "Enter your details" form in carts file

### ISSUE THREAD

**Issue by SumithThota** [Anushkabh/krishiconnect#656] opened 2024-06-22 07:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

User Unable to insert data into "Enter your details" form in carts file.
Check this video once:

https://github.com/Anushkabh/krishiconnect/assets/108344062/1338de28-5d86-4c9d-8725-5af06bc2f1e9

Let me fix this issue as a GSSOC224v Contributor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment] 2024-06-30 07:30
Hello @SumithThota !

The issue is already been fixed and merged in our repo.
Kepp looking for morre issues in the repo.

Happy Coding ✨

**Closed by himanshu-03** 2024-06-30 07:30 UTC
