### ISSUE TITLE
Feat: Adding links to respective sections of vegetables,fruits etc in shop section .

### ISSUE THREAD

**Issue by Maana-Ajmera** [Anushkabh/krishiconnect#688] opened 2024-06-29 21:06 UTC
### Describe the feature

- Links in the footer of shop section named herbs , fruits etc. should point to their respective section on their page.
- Also, since their is no section for pulses , but their is a link for pulses in footer , we can create a similar section for pulses as well.

### Add ScreenShots

Before:

https://github.com/Anushkabh/krishiconnect/assets/162733812/29728ac5-7fa1-47c1-a270-4be2cee6bd21

After :

https://github.com/Anushkabh/krishiconnect/assets/162733812/42dabc59-e1f2-4a93-8132-1f735fab8dec

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment] 2024-06-29 21:08
@himanshu-03 I want to work on this issue , please assign it to me

**Comment by himanshu-03** [comment] 2024-06-30 07:48
hello @Maana-Ajmera !

The repo is currently undergoing many changes wrt the footer. Once it is updated you can start working on this issue..

happy coding ✨

**Comment by himanshu-03** [comment] 2024-07-01 07:30
Hey @Maana-Ajmera !

Do you want to work on this issue or not?
We have updated the footer.

**Comment by Maana-Ajmera** [comment] 2024-07-01 09:56
@himanshu-03 yes , I will work on this issue...Thank you!

**Comment by Maana-Ajmera** [comment] 2024-07-01 10:17
@himanshu-03 should I also modify the footer as mentioned in issue https://github.com/Anushkabh/krishiconnect/issues/712 ?

**Comment by himanshu-03** [comment] 2024-07-01 12:11
hey @Maana-Ajmera !

The issue is been assigned to someone else along with the modification of logo in the footer
Please keep looking for new changes in the repo.

happy coding ✨

**Closed by himanshu-03** 2024-07-01 12:11 UTC
Labels: gssoc, queue

**Comment by Maana-Ajmera** [comment] 2024-07-01 12:13
@himanshu-03 I have already linked all the pages...if you want I can create the PR for it

**Comment by himanshu-03** [comment] 2024-07-01 12:15
> @himanshu-03 I have already linked all the pages...if you want I can create the PR for it

The footer is changed in our website now. Have you done your changes in the updated footer?

**Comment by Maana-Ajmera** [comment] 2024-07-01 12:18
> > @himanshu-03 I have already linked all the pages...if you want I can create the PR for it
> 
> The footer is changed in our website now. Have you done your changes in the updated footer?

yes..

**Comment by himanshu-03** [comment] 2024-07-01 12:42
> @himanshu-03 I did it like this , and also modified the logo
> 
>  Screen.Recording.2024-07-01.at.6.07.30.PM.mov

Hey @Maana-Ajmera !

But modifying the logo was assigned to someone else before you today. Its on FCFS basis

**Comment by himanshu-03** [comment] 2024-07-01 12:42
You can keep looking for more issues in the repo.

There will be few good issues created in next some days in the repo.
Keep an eye on them.

**Comment by Maana-Ajmera** [comment] 2024-07-01 12:45
@himanshu-03 sure ! Thank you.
