### ISSUE TITLE
BUG:  Wishlist Page Shows 404 Error on First Click

### ISSUE THREAD

**Issue by KajalBhatt123** [Anushkabh/krishiconnect#725] opened 2024-07-01 15:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an issue with the wishlist page on the website where it shows a 404 error the first time it is accessed. However, after filling in something in the wishlist and clicking the link again, the page loads correctly. This inconsistent behavior affects the user experience as users encounter a broken link on their initial attempt to access the wishlist.

Steps to Reproduce:

Navigate to the website.
Click on the "Wishlist" link for the first time.
Observe that a 404 error page is displayed.
Add an item to the wishlist.
Click on the "Wishlist" link again.
Observe that the wishlist page loads correctly.

Expected Behavior:
The wishlist page should load correctly on the first click without showing a 404 error.

![Screenshot 2024-07-01 210727](https://github.com/Anushkabh/krishiconnect/assets/133188585/73539cf9-63d1-46b8-b4e7-b2d5b720e393)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KajalBhatt123** [comment] 2024-07-02 04:20
@himanshu-03 kindly assign

**Comment by himanshu-03** [comment] 2024-07-02 08:39
hey @KajalBhatt123 !

You started working on and created a PR without getting approved, the issue is already been addressed by someone else.
Keep looking for more issues in the repo..
happy coding ✨

**Closed by himanshu-03** 2024-07-02 08:39 UTC
