### ISSUE TITLE
improving the UI of the pages

### ISSUE THREAD

**Issue by 777advait** [Anushkabh/krishiconnect#21] opened 2024-05-10 13:37 UTC
<img width="1144" alt="image" src="https://github.com/Anushkabh/krishiconnect/assets/76993204/013bff39-3d3c-4f46-8715-77859840650d">
the cards can be made to be of the same size

**Comment by Jamir2412** [comment] 2024-05-10 13:49
@Anushkabh can you add a label "gssoc" label and "level "?

**Comment by Niranjan5601** [comment] 2024-05-10 14:20
Hi @777advait can you please assign me the issue?

**Comment by sakshiiiii26** [comment] 2024-05-10 20:26
Hello!! @Anushkabh  I am a contributor of GSSoC 24 and I would like to design this page in attractive way. So I request you to please assign me this task thankyou!!

**Comment by Anushkabh** [comment] 2024-05-11 17:36
@777advait go ahead!
@sakshiiiii26  @Niranjan5601 @Jamir2412 we assign issues on a first-come, first-served basis. If someone fails to raise a pr within the time frame, then the issue is passed to another person, order-wise

**Comment by 777advait** [comment] 2024-05-12 10:49
thank you @Anushkabh 
i just had one doubt, am i allowed to contribute to only the issues that i've been assigned or i can contribute to any issues with GSSoC tag?

**Comment by Jamir2412** [comment] 2024-05-12 11:18
> thank you @Anushkabh i just had one doubt, am i allowed to contribute to only the issues that i've been assigned or i can contribute to any issues with GSSoC tag?

your PR will not be accepted if you were not assigned to that issue.

**Comment by himanshu-03** [comment] 2024-06-14 14:00
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!

**Closed** 2024-06-14 15:52 UTC
Labels: wontfix
