### ISSUE TITLE
Feat: : Implement a 404 Not Found Page

### ISSUE THREAD

**Issue by HarshadaGirase** [Anushkabh/krishiconnect#753] opened 2024-07-02 17:46 UTC
### Describe the feature

Feature Request: Implement a 404 Not Found Page
Title: Implement a 404 Not Found Page

Description:
Create a custom 404 Not Found page to improve user experience when visitors encounter broken links or try to access nonexistent pages on the website. The 404 page should be informative, user-friendly, and consistent with the site's desig

### Add ScreenShots

![notfound](https://github.com/Anushkabh/krishiconnect/assets/128895955/04774206-fe2c-4e30-968b-3795d0629cf2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment] 2024-07-03 05:14
Hello @HarshadaGirase !

Someone is already assigned this issue, if they fail to do so you will be pinged and assigned the issue

**Comment by HarshadaGirase** [comment] 2024-07-03 05:46
Okay but kindly assign asap

**Comment by himanshu-03** [comment] 2024-07-05 06:37
The issue is already addressed.

**Closed by himanshu-03** 2024-07-05 06:37 UTC
Labels: gssoc, queue
