### ISSUE TITLE
Feat: Optimising the chatbot

### ISSUE THREAD

**Issue by Dilpreet0501** [Anushkabh/krishiconnect#649] opened 2024-06-21 10:28 UTC
### Describe the feature

Hello @Anushkabh , I would like to optimise the chatbot and add a menu so that bot can easily ask users' questions.
Kindly assign me this issue under GSSoC'24. I'll do my best.

### Add ScreenShots

![Screenshot 2024-06-21 155403](https://github.com/Anushkabh/krishiconnect/assets/100590445/2a4f47bd-acc4-401f-bff0-fa62002d03f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adityasingh-0803** [comment] 2024-06-28 14:18
@Anushkabh i can work on it please assign

**Comment by himanshu-03** [comment] 2024-07-05 06:47
Hey @Dilpreet0501 !

Its been a long time since u were assigned and theres no reply from your side, the issue is assigned to someone else.

**Closed by himanshu-03** 2024-07-05 06:47 UTC
Labels: gssoc, level1

**Comment by Dilpreet0501** [comment] 2024-07-06 05:30
Hello @himanshu-03 , I'm working on it, please reassign me, I will make sure to complete it by tomorrow
